In [7]:
import pandas as pd
import csv
import tensorflow as tf
from tensorflow import keras
import numpy as np
import json
import ast

import collections
import pathlib
import tensorflow as tf
import pandas as pd
import csv
from tensorflow import keras
import numpy as np
from tensorflow.keras import layers
from tensorflow.keras import losses
from tensorflow.keras import utils
from tensorflow.keras.layers import TextVectorization

In [8]:
datasetRead = pd.read_csv('dataset.csv')
print(datasetRead.shape)

(74199, 18)


In [9]:
x = datasetRead.values[:,0:14]
y = datasetRead.values[:,14:18]

for i in range(len(x)):
    x[i][4] = ast.literal_eval(x[i][4] )
    x[i][10] = ast.literal_eval(x[i][10])
    x[i][12] = ast.literal_eval(x[i][12])
    
#x = tf.convert_to_tensor(x, dtype=tf.float32)

In [10]:
print(x)

[[0.00969284 -0.982 0 ... 0.333666 list([0.0, 0.0, 0.0, 0.0])
  -0.000184746]
 [0.00969284 -0.962 0 ... 0.333666 list([0.0, 0.0, 0.0, 0.0])
  -0.000184746]
 [0.00969284 -0.942 0 ... 0.333666 list([0.0, 0.0, 0.0, 0.0])
  -0.000184746]
 ...
 [1.45062 35.072 956 ... -2.0627
  list([1.74705, 0.207567, 1.20531, -0.724672]) -0.00142574]
 [1.45062 35.094 956 ... -2.0627
  list([1.30277, -1.33756, 0.739967, 0.772104]) -0.000720113]
 [1.45061 35.116 956 ... -2.0627
  list([-0.583776, -0.849354, -0.853659, 1.08554]) -0.000849075]]


In [11]:
print(y)

[[0.1 0.0 1 0.0]
 [0.1 0.0 1 0.0]
 [0.1 0.0 1 0.0]
 ...
 [0.1 0.0 1 0.0]
 [0.1 0.0 1 0.0]
 [0.1 0.0 1 0.0]]


In [14]:
abalone_model = tf.keras.Sequential([
  layers.Dense(64),
  layers.Dense(1)
])

abalone_model.compile(loss = tf.keras.losses.MeanSquaredError(),
                      optimizer = tf.optimizers.Adam())

# abalone_model.fit(x,y, epochs=10)

ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type float).

In [ ]:
gameModel = keras.Sequential([
    keras.layers.Dense(units=256, input_shape=(19,), activation='relu'),
    keras.layers.Dense(units=192, activation='relu'),
    keras.layers.Dense(units=128, activation='relu'),
    keras.layers.Dense(units=1, activation='softmax')
])

In [ ]:
gameModel.compile(optimizer='adam', 
              loss='mean_squared_error',
              metrics=['accuracy'])

In [ ]:
gameModel.fit(x,y,epochs=50,batch_size=30,verbose=1)